### ISSUE TITLE
A problem occurred

### ISSUE THREAD

**Issue by elyonardo** [xavidop/voiceflow-alexa-integration#4]
Hi!
I tried to import your VoiceFlow project in my dashboard but it returns an ".VF file failed to import" error.
Anyway, I tried to build something similar and alexa should simply answers "Your skill is working".
I created the info_intent intent and the utterances.
I added the info_intent in the Interaction Model section of ASK, I added an Invocation name, I copied your code in index.js and util.js and I replaced my API Key in util.js.
But, when I try to test the skill it returns "There was a problem with the response of the requested skill" error.

What am I doing wrong?

Thanks!

**Comment by xavidop** [comment]
Please, contact voiceflow support to address these issues
